var wolfzqTextCH = {
	'language': 'Language',
	'version': '2.50 translate 100%',
	'relogin': 'Relogin',
	't0': 'Horny Girl',
	't1': 'Estrus Slut', 't2': 'Promiscuous Bitch',  't3': 'Sperm-sucking Pink',  't4': 'Sperm Killer',  't5': 'Limitless Pussy',  't6': 'Anal Addict',  't7': 'Anal Maniac',  't8': 'Anal Princess',  't9': 'Exhibitionism Addict',  't10': 'Exhibitionism Madness', 
	't11': 'Exhibitionism Poisoning', 't12': 'Cum Swallowing Hobby',  't13': 'Sperm Addict',  't14': 'Sperm Slave',  't15': 'Incontinent Princess',  't16': 'Scat Princess',  't17': 'Public Toilet',  't18': 'Sadism Addict',  't19': 'Sadism Maniac',  't20': 'SM Queen',
	't21': 'Masochism Addict', 't22': 'Masochism Maniac',  't23': 'SM Slave',  't24': 'Exhibitionism Addict',  't25': 'Exhibitionism Maniac',  't26': 'Exhibitionism Princess',  't27': 'Macromastia Girl',  't28': 'Milk Slave',  't29': 'Milk Cattle',  't30': 'Yuri Princess',
	't31': 'Seedbed', 't32': 'Futanari',  't33': 'Spray Poisoning',  't34': 'Hundred Overkill',  't35': 'Thousand Overkill', 't36': 'Urine Drinking Fetish', 't37': 'Urine Addict', 't38': 'Pee Slave',  't39': 'Real Toilet',
	't0memo': 'Becomes more and more lustful, gets title when fall reaches 10',
	't1memo': 'Wants to have sex anytime, gets title when fall reaches 500', 't2memo': 'It doesn\'t matter the object of sex is human or not, gets title when fall reaches 2000',
	't3memo': 'Gets title when Sex Count is more than 10',  't4memo': 'Gets title when Sex Count is more than 500',
	't5memo': 'Gets title when Sex Count is more than 2000',  't6memo': 'Gets title when Anal Count is more than 10',  
	't7memo': 'Gets title when Anal Count is more than 500',  't8memo': 'Gets title when Anal Count is more than 2000',
	't9memo': 'Gets title when Masturbation Count is more than 10',  't10memo': 'Gets title when Masturbation Count is more than 500', 
	't11memo': 'Gets title when Masturbation Count is more than 2000', 't12memo': 'Gets title when Swallow Count is more than 10',
	't13memo': 'Gets title when Swallow Count is more than 500',  't14memo': 'Gets title when Swallow Count is more than 2000',
	't15memo': 'Gets title when Urination Count is more than 100',  't16memo': 'Gets title when Scat Count is more than 100',
	't17memo': 'Gets title when Sperm Bath Count is more than 100',  't18memo': 'Gets title when Sadism Count reaches 10',
	't19memo': 'Gets title when Sadism Count reaches 500',  't20memo': 'Gets title when Sadism Count reaches 2000',
	't21memo': 'Gets title when Masochism Count reaches 10', 't22memo': 'Gets title when Masochism Count reaches 500',
	't23memo': 'Gets title when Masochism Count reaches 2000',  't24memo': 'Gets title when Exhibitionism Count is more than 10',
	't25memo': 'Gets title when Exhibitionism Count is more than 500',  't26memo': 'Gets title when Exhibitionism Count is more than 2000',
	't27memo': 'Gets title when Milking Count is more than 10',  't28memo': 'Gets title when Milking Count is more than 500',
	't29memo': 'Gets title when Milking Count is more than 2000',  't30memo': 'Gets title when Yuri Count is more than 100',
	't31memo': 'Gets title when Birth Count is more than 100', 't32memo': 'Get title after body modification',
	't33memo': 'Needs in Futanari status, gets title when Shot Count is more than 100',  't34memo': 'Needs in Estrus status，gets title Exploit Count(charm and have sex with human) is more than 100',
	't35memo': 'Needs in Estrus status，gets title Exploit Count(charm and have sex with human) is more than 1000',
	't36memo': 'Gets title when Urophagia Count is more than 10',
	't37memo': 'Gets title when Urophagia Count is more than 500',  't38memo': 'Gets title when Urophagia Count is more than 2000',
	't39memo': 'Gets title when Urine Bath Count is more than 10',

	'job0': 'Ordinary Citizen', 'job1': 'Junior Member', 'job2': 'Intermediate Member', 'job3': 'Senior Member', 'job4': 'Master Member', 'job5': 'Angel Hunter', 
	'sexjob0': '', 'sexjob1': 'Prostitute', 'sexjob2': 'Prostitute', 'sexjob3': 'Sex Slave', 'sexjob4': 'Meat Urinal', 'sexjob5': 'Worm Wife', 'sexjob6': 'Unicorn Wife', 'sexjob7': 'Forever Sex Slave', 'sexjob8': 'Slave Dancing Queen',

	'sex': 'Sex Count', 'ass': 'Analsex Count', 'ipsation': 'Masturbation Count', 'mouth': 'Oral Count', 'breast': 'Titfuck Count', 'sperm': 'Swallow Count', 'urine': 'Urophagia Count', 'urinebath': 'Urine Bath Count', 
	'milk': 'Milking Count', 
	'pee': 'Urination Count', 'shit': 'Scat Count', 'high': 'Orgasm Count', 'shoot': 'Shot Count', 'born': 'Birth Count', 'bath': 'Sperm Bath Count', 'show': 'Exhibitionism Count', 
	'girl': 'Yuri Count', 'vent': 'Exploit Count', 'milkml': 'In-vivo Milk(ML)', 'spermml': 'Intrauterine Sperm(ML)', 

	'repute': 'Repute', 'charm': 'Charm', 'reason': 'Reason', 'lust': 'Lust', 'fall': 'Fall', 'cursed': 'Curse', 'mother': 'Maternal', 's': 'Sadism', 'm': 'Masochism', 
	'shame': 'Shame', 'submission': 'Submission', 'obscene': 'Sexual Power', 'god': 'God Power',
		
	'KeyConfig': 'Push Button Configuration','KeyConfigDefault': 'Restore to the initial setting','KeyConfigLayout': 'WASD Setting','KeyConfigFinish': 'Save settings','KeyConfigHelp': 'Sure to change the keyboard settings?',
	'KeyConfigDefaultHelp': 'Restore default settings','KeyConfigLayoutHelp': 'Change control type to WASD','KeyConfigFinishHelp': 'Sure to save the keyboard settings?','KeyConfigButtonClear': 'Clear',
	'KeyConfigButtonOk': 'Confirm/Talk（O/T）','KeyConfigButtonEsc': 'Cancel/Menu（C/M）','KeyConfigButtonCancel': 'Cancel（C）','KeyConfigButtonMenu': 'Menu（Menu）',
	'KeyConfigButtonDash': 'Dash（R/W）','KeyConfigButtonPageUp': 'Page Up（PgUp）','KeyConfigButtonPageDown': 'Page Down（PgDn）',
	'KeyConfigButtonLeft': 'Move Left（?）','KeyConfigButtonUp': 'Move Up（▲）','KeyConfigButtonRight': 'Move Right（?）','KeyConfigButtonDown': 'Move Down（▼）',
	'KeySkip': 'Accelerate Story（Skip）','KeyWardrobe': 'Quick Change Outfits（Ward）','KeyMimicry': 'Mimicry（Mimi）','KeyUseSkill': 'Slut（Skill）',

	'Steps': 'Steps', 'Rewards': 'Rewards',	'NoQuest':'No Quests','All':'All','Completed':'Completed','Failed':'Failed','InProgress':'In-Progress',

	'p1': 'Upgrade to be: ', 'p2': 'A large number of sperm overflow from womb...','p3': 'Milk keep overflowing from tits...','p4': 'Got Title:','p5': 'Got ','p6': 'Lost ','p7': 'Virgin','p8': 'Title List','p9': 'Clothes of Lilina can\'t be taken off!','p10': 'But Lilina has evaded!',
	'p11': 'Cursed Armor dispears miraculously!', 'p12': 'Needs Shackle(feet)','p13': 'Needs Shackle(hands)','p14': 'Got Sex Title:','p15': ' Regenerate Hp','p16': 'Not Virgin',
	'p17': 'Missing picture! Failed to load:',
	'p18': 'Missing picture! Patreons only, please check the Patreon on the start screen if interested.' ,'p19': '(\\W[4] popped her cherry)',

	'p20': 'Obscene Synthesis, Normal Synthesis', 'p21': 'Sell','p22': 'Equipment','p23': 'Type','p24': 'Material：','p25': 'Successful：','p26': 'Not enough money!','p27': 'Memorandum [','p28': '] updated！','p29': 'Lilina is pregnant!',
};

var wolfzqTextJP = {
	'language': 'Language',
	'version': '2.50',
	'relogin': '重登陸',
	't0': 'エッチな少女',
	't1': '発情女', 't2': '牝犬',  't3': '吸精マ〇コ',  't4': '精子搾り',  't5': '底なしマ〇コ',  't6': 'アナル好き',  't7': 'アナルマニア',  't8': 'アナル姫',  't9': '自慰好き',  't10': '自慰マニア', 
	't11': '自慰中毒', 't12': '精飲癖',  't13': '精子中毒',  't14': '精子奴隷',  't15': '漏らし姫',  't16': 'クソ姫',  't17': '肉便器',  't18': 'S',  't19': 'ドS',  't20': '女王',
	't21': 'M', 't22': 'ドM',  't23': '奴隷',  't24': '露出癖',  't25': '露出マニア',  't26': '露出姬',  't27': '巨乳少女',  't28': '乳奴隷',  't29': '乳牛',  't30': 'ユリ姬',
	't31': '苗床', 't32': 'ふたなり',  't33': '射精中毒',  't34': '百人斬り',  't35': '千人斬り', 't36': 'おしっこ好き',  't37': 'おしっこ中毒',  't38': 'おしっこ奴隷',  't39': '真·便器',
	't0memo': 'だんだんエッチな子になっている。墮落さが10を越えたら得られる',
	't1memo': 'いつでもエッチなことがしたい。墮落さが500を越えたら得られる', 't2memo': '相手はなんでもいい。墮落さが2000を越えたら得られる',
	't3memo': '性交回數が10を越えたら得られる。', 't4memo': '性交回數が500を越えたら得られる',
	't5memo': '性交回數が2000を越えたら得られる。',  't6memo': 'アナルセックス回數が10を越えたら得られる。',  
	't7memo': 'アナルセックス回數が500を越えたら得られる',  't8memo': 'アナルセックス回數が2000を越えたら得られる',
	't9memo': '自慰する回數が10を越えたら得られる',  't10memo': '自慰する回數が500を越えたら得られる', 
	't11memo': '自慰する回數が2000を越えたら得られる', 't12memo': '精子を飲む回數が10を越えたら得られる',
	't13memo': '精子を飲む回數が500を越えたら得られる',  't14memo': '精子を飲む回數が2000を越えたら得られる',
	't15memo': '100回以上漏らしたら得られる',  't16memo': '100回以上脫糞されたら得られる',
	't17memo': '100回以上ぶっかけされたら得られる',  't18memo': 'S行為10回を越えたら得られる',
	't19memo': 'S行為500回を越えたら得られる',  't20memo': 'S行為2000回を越えたら得られる',
	't21memo': 'M行為10回を越えたら得られる', 't22memo': 'M行為500回を越えたら得られる',
	't23memo': 'M行為2000回を越えたら得られる',  't24memo': '露出回數が10回を越えたら得られる',
	't25memo': '露出回數が500回を越えたら得られる',  't26memo': '露出回數が2000回を越えたら得られる',
	't27memo': '乳搾り回數が10回を越えたら得られる',  't28memo': '乳搾り回數が500回を越えたら得られる',
	't29memo': '乳搾り回數が2000回を越えたら得られる',  't30memo': '同性行為が100回を越えたら得られる',
	't31memo': '出産回數が100回を越えたら得られる', 't32memo': '肉體改造で得られる',
	't33memo': 'ふたなり狀態で100回射精したら得られる',  't34memo': '誘惑してセックスする人間の數が100を越えたら得られる',
	't35memo': '誘惑してセックスする人間の數が1000を越えたら得られる',
	't36memo': '飲尿回數が10を越えたら得られる',
	't37memo': '飲尿回數が500を越えたら得られる',  't38memo': '飲尿回數が2000を越えたら得られる',
	't39memo': '需要尿浴次數超過10次',

	'job0': '市民', 'job1': '初級會員', 'job2': '中級會員', 'job3': '高級會員', 'job4': 'VIP', 'job5': '狩天使',
	'sexjob0': '', 'sexjob1': '売女', 'sexjob2': '娼婦', 'sexjob3': '性奴隸', 'sexjob4': '肉便器', 'sexjob5': '蟲妻', 'sexjob6': '獸妻', 'sexjob7': '永久性奴隸', 'sexjob8': '性奴舞后',

	'sex': 'セックス回數', 'ass': 'アナルセックス回數', 'ipsation': '自慰回數', 'mouth': 'しゃぶり回數', 'breast': '乳挾み回數', 'urine': '尿飲み回數', 'sperm': '精飲回數', 'milk': '乳搾り回數', 
	'pee': '漏らし回數', 'shit': '排便回數', 'high': '絶頂回數', 'shoot': '射精回數', 'born': '出産回數', 'bath': 'ぶっかけ回數', 'urinebath': '尿浴回數', 'show': '露出回數', 
	'girl': '同性行為回數', 'vent': '欲望解放回數', 'milkml': '母乳量(ML)', 'spermml': '精子量(ML)', 

	'repute': '名譽', 'charm': '魅力', 'reason': '理性', 'lust': '欲望', 'fall': '墮落', 'cursed': '呪い', 'mother': '母性', 's': 'S', 'm': 'M', 
	'shame': '羞恥', 'submission': '従順度', 'obscene': '淫欲', 'god': '神性',
			
	'KeyConfig': 'キーコンフィグ','KeyConfigDefault': 'デフォルトレイアウト','KeyConfigLayout': 'WASDレイアウト','KeyConfigFinish': 'コンフィグを完了','KeyConfigHelp': 'このキーのコンフィグを変更しますか？',
	'KeyConfigDefaultHelp': 'キーボード設定をデフォルトに戻します','KeyConfigLayoutHelp': 'キーボードをWASDレイアウトに変更します','KeyConfigFinishHelp': 'キーボードのコンフィグを完了しますか？','KeyConfigButtonClear': 'Clear',
	'KeyConfigButtonOk': 'OK / 話す（O/T）','KeyConfigButtonEsc': 'Cancel / Menu（C/M）','KeyConfigButtonCancel': 'キャンセル（C）','KeyConfigButtonMenu': 'Menu（Menu）',
	'KeyConfigButtonDash': 'ダッシュする（R/W）','KeyConfigButtonPageUp': 'ページアップ（PgUp）','KeyConfigButtonPageDown': 'ページダウン（PgDn）',
	'KeyConfigButtonLeft': '左へ（?）','KeyConfigButtonUp': '上へ（▲）','KeyConfigButtonRight': '右へ（?）','KeyConfigButtonDown': '下へ（▼）',
	'KeySkip': 'ストーリーを速める（Skip）','KeyWardrobe': 'ショートカット換衣（Ward）','KeyMimicry': '擬態（Mimi）','KeyUseSkill': '淫技（Skill）',

	'Steps': '進度', 'Rewards': '奨勵',	'NoQuest':'沒有任務','All':'全部','Completed':'已完成','Failed':'已失敗','InProgress':'進行中',

	'p1': '進化：： ', 'p2': '大量の精子が子宮から溢れてきた…','p3': '乳がのおっぱいから溢れてきた…','p4': '稱號を獲得：','p5': '獲得 ','p6': '失った ','p7': '処女','p8': '稱號一覧','p9': 'リリナの服は脫げない！','p10': 'リリナが避けました！',
	'p11': '呪いの鎧は消えました！', 'p12': '足かせが必要','p13': '手かせが必要','p14': '性稱號を獲得：','p15': 'が癒られた','p16': '','p17': '','p18': '','p19': '（\\W[4]）',
	'p20': '淫能合成, 普通合成', 'p21': '售價','p22': '裝備','p23': '類型','p24': 'タイプ：','p25': '合成成功：','p26': 'お金は足りない!',
	'p27': '備考録[','p28': ']更新！','p29': 'リリナ妊娠しました!',
};

var $wolfzqWebText = {
	'username': '用戶名必須為3-40個字符！',
	'password': '用戶密碼必須為6-40個字符！',
	'passwordError': '用戶名或密碼不正確！',
	'passwordError1': '新密碼輸入不一致！',
	'txt1': '賬號：',
	'txt2': '密碼：',
	'txt3': '舊密碼：',
	'txt4': '新密碼：',
	'txt5': '確認密碼：',
	'txt6': '登錄',
	'txt7': '修改密碼',
	'txt8': '保存',
	'txt9': '返回',
	'txt10': '請妥善保管自己的賬號密碼，以免泄露后造成賬號被封停！',
	'txt11': '密碼必須是6位以上字母和數字的組合！',
	'txt12': '忘記密碼？',
	'txt1101': '用戶名或密碼錯誤！',
	'txt1102': '賬戶已經被禁用！',
	'txt1105': '登陸失敗次數過多，賬號鎖定1小時！',
};

var wolfzqText = {
	'language': '語言選擇',
	'version': '2.50',
	'relogin': '重登陸',
	't0': '好色少女',
	't1': '發情淫女', 't2': '淫亂雌獸',  't3': '吸精騷穴',  't4': '榨精名器',  't5': '無底淫穴',  't6': '肛交癖',  't7': '肛交狂',  't8': '肛交姬',  't9': '自慰癖',  't10': '自慰狂', 
	't11': '自慰中毒', 't12': '飲精癖',  't13': '精液中毒',  't14': '精液奴隸',  't15': '失禁姬',  't16': '排泄姬',  't17': '公共便器',  't18': '施虐癖',  't19': '施虐狂',  't20': 'SM女王',
	't21': '受虐癖', 't22': '受虐狂',  't23': 'SM奴隸',  't24': '露出癖',  't25': '露出狂',  't26': '露出姬',  't27': '巨乳少女',  't28': '乳奴隸',  't29': '乳家畜',  't30': '百合姬',
	't31': '苗床', 't32': '雙性人',  't33': '射精中毒',  't34': '百人斬',  't35': '千人斬', 't36': '飲尿癖',  't37': '尿中毒',  't38': '尿奴隸',  't39': '真·便器',
	't0memo': '變得越來越好色了，墮落度達到10獲得',
	't1memo': '什么時候都想要做色色的事，墮落度達到500獲得', 't2memo': '對象是不是人已經不重要了，墮落度達到2000獲得',
	't3memo': '需要性交次數超過10次',  't4memo': '需要性交次數超過500次',
	't5memo': '需要性交次數超過2000次',  't6memo': '需要肛交次數超過10次',  
	't7memo': '需要肛交超過500次',  't8memo': '需要肛交次數超過2000次',
	't9memo': '需要自慰次數超過10次',  't10memo': '需要自慰次數超過500次', 
	't11memo': '需要自慰次數超過2000次', 't12memo': '需要飲精次數超過10次',
	't13memo': '需要飲精次數超過500次',  't14memo': '需要飲精次數超過2000次',
	't15memo': '需要失禁次數超過100次',  't16memo': '需要排泄次數超過100次',
	't17memo': '需要精浴次數超過100次',  't18memo': '施虐達到10獲得',
	't19memo': '施虐達到500獲得',  't20memo': '施虐達到2000獲得',
	't21memo': '受虐達到10獲得', 't22memo': '受虐達到500獲得',
	't23memo': '受虐達到2000獲得',  't24memo': '需要露出次數超過10次',
	't25memo': '需要露出次數超過500次',  't26memo': '需要露出次數超過2000次',
	't27memo': '需要榨乳次數超過10次',  't28memo': '需要榨乳次數超過500次',
	't29memo': '需要榨乳次數超過2000次',  't30memo': '需要百合次數超過100次',
	't31memo': '需要出產次數超過100次', 't32memo': '肉體被改造后獲得',
	't33memo': '需要FUTA狀態后射精次數超過100次',  't34memo': '需要在發情狀態，誘惑并推倒人類總數達到100次',
	't35memo': '需要在發情狀態，誘惑并推倒人類總數達到1000次',
	't36memo': '需要飲尿次數超過10次',
	't37memo': '需要飲尿次數超過500次',  't38memo': '需要飲尿次數超過2000次',
	't39memo': '需要尿浴次數超過10次',

	'job0': '普通市民', 'job1': '初級會員', 'job2': '中級會員', 'job3': '高級會員', 'job4': '資深會員', 'job5': '獵天使', 
	'sexjob0': '', 'sexjob1': '賣淫女', 'sexjob2': '娼淫的妓女', 'sexjob3': '性奴隸', 'sexjob4': '肉便器', 'sexjob5': '蟲妻', 'sexjob6': '獸妻', 'sexjob7': '永久性奴隸', 'sexjob8': '性奴舞后',

	'sex': '性交次數', 'ass': '肛交次數', 'ipsation': '自慰次數', 'mouth': '口交次數', 'breast': '乳交次數', 'urine': '飲尿次數', 'sperm': '飲精次數', 'milk': '榨乳次數', 
	'pee': '失禁次數', 'shit': '排泄次數', 'high': '高潮次數', 'shoot': '射精次數', 'born': '出產次數', 'bath': '精浴次數', 'urinebath': '尿浴次數', 'show': '露出次數', 
	'girl': '百合次數', 'vent': '泄欲次數', 'milkml': '體內乳汁(ML)', 'spermml': '淫穴精液(ML)', 

	'repute': '名聲', 'charm': '魅力', 'reason': '理性', 'lust': '欲望', 'fall': '墮落', 'cursed': '詛咒', 'mother': '母性', 's': '施虐', 'm': '被虐', 
	'shame': '羞恥', 'submission': '順從', 'obscene': '淫能', 'god': '神性',

	'KeyConfig': '按鍵配置','KeyConfigDefault': '恢復初期設定','KeyConfigLayout': 'WASD設定','KeyConfigFinish': '保存設定','KeyConfigHelp': '要更換當前按鍵設定嗎？',
	'KeyConfigDefaultHelp': '按鍵設定恢復初始','KeyConfigLayoutHelp': '移動模式變更為WASD','KeyConfigFinishHelp': '確認保存按鍵設定嗎？','KeyConfigButtonClear': '清除按鍵',
	'KeyConfigButtonOk': '確認/對話（O/T）','KeyConfigButtonEsc': '取消/菜單（C/M）','KeyConfigButtonCancel': '取消（C）','KeyConfigButtonMenu': '菜單（Menu）',
	'KeyConfigButtonDash': '快速移動（R/W）','KeyConfigButtonPageUp': '上一頁（PgUp）','KeyConfigButtonPageDown': '下一頁（PgDn）',
	'KeyConfigButtonLeft': '左移（?）','KeyConfigButtonUp': '上移（▲）','KeyConfigButtonRight': '右移（?）','KeyConfigButtonDown': '下移（▼）',
	'KeySkip': '加速演出（Skip）','KeyWardrobe': '快捷換裝（Ward）','KeyMimicry': '擬態（Mimi）','KeyUseSkill': '淫技（Skill）',

	'Steps': '進度', 'Rewards': '獎勵',	'NoQuest':'沒有任務','All':'全部','Completed':'已完成','Failed':'已失敗','InProgress':'進行中',

	'p1': '升級成為： ', 'p2': '大量精液從子宮里溢出……','p3': '乳汁不斷的從乳首溢出……','p4': '獲得稱號：','p5': '獲得 ','p6': '失去 ','p7': '處女','p8': '稱號一覽','p9': '莉莉娜身上的外衣無法被脫去！','p10': '但被莉莉娜躲過了！',
	'p11': '詛咒鎧甲奇跡般的消失了！', 'p12': '需要鐐銬(腳)','p13': '需要鐐銬(手)','p14': '獲得性稱號：','p15': '被治愈','p16': '非處女',
	'p17': '缺少圖片了！請截圖聯系開發者！圖片地址：',
	'p18': '缺少圖片了！該圖片可能需要參與眾籌后獲得，有興趣請參看游戲開始界面的Patreon了解。','p19': '（被\\W[4]破處）',
	'p20': '淫能合成, 普通合成', 'p21': '售價','p22': '裝備','p23': '類型','p24': '材料：','p25': '合成成功：','p26': '錢好像不夠了！','p27': '備忘錄中，[','p28': ']有新進展！','p29': '莉莉娜懷孕了！',
};